baseURL = 'https://baanpolballs.co/'

title = 'บ้านผลบอล สรุปผลบอล ผลบอลสด ทีเด็ดบอล ก่อนแข่งทุกวัน'
LanguageCode='th'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']
sectionPagesMenu = 'main'
[markup.highlight]
  noClasses = false

[Params]
  description = "บ้านผลบอล สรุปผลบอล baanpolballs ผลบอลสด ทีเด็ดบอล ทรรศนะบอล ทีเด็ดบอลวันนี้ ดูผลบอลเมื่อคืน ไฮไลท์ฟุตบอลเมื่อคืน ดูบอลสดไม่กระตุก เว็บดูบอลสดที่เร็วที่สุด 2023"

[Params.social]
  github = 'https://github.com/baanpolballs'
  linkedin = 'https://www.linkedin.com/in/baanpolballs/'
  twitter = 'https://twitter.com/baanpolballs'


[build]
  writeStats = true

[caches]
  [caches.getjson]
    maxAge = "10m"


